### ISSUE TITLE
Can't invite game to server

### ISSUE THREAD

**Issue by Nitapitabread** [chevtek/holdem-bot#2]
It gives the old comment about verification needed from the developer.

**Comment by AlexAllocated** [comment]
I see the issue now. I have submitted my verification;. Discord may not approve it until after the US holiday weekend. I'll update here when I get confirmation.

**Comment by AlexAllocated** [comment]
The verification application is still pending. Just wanted to update to let you know I haven't forgotten. Discord is being very slow to approve it.

**Comment by AlexAllocated** [comment]
Still waiting on discord support. They reached out for additional information on how the bot is hosted. I provided it two days ago and have heard nothing back. I'm replying to the ticket once a day to see if there's anything I can do to help push it along. So far we going on two days without correspondence. I'll keep updating you guys but my hands are still tied.

**Comment by chevsunrun** [comment]
FINALLY the bot has been approved.

**Comment by chevsunrun** [comment]
No response all week and then it's approved on a Saturday night... ¯\_(ツ)_/¯

**Comment by AlexAllocated** [comment]
The bot has finally been approved. On a Saturday night no less ¯\\_(ツ)_/¯
